export const pizzaData = [
  {
    id: 1,
    title: "Shawarma Pizza",
    img: "/images/pizza.webp",
    desc: "Spicy chicken, red onions, tomatoes, mozzarella, mayonnaise, ketchup, peri peri",
    prices: [12, 13, 14],
  },
  {
    id: 2,
    title: "Margherita Pizza",
    img: "/images/pizza.webp",
    desc: "Fresh tomato sauce, mozzarella, basil",
    prices: [10, 11, 12],
  },
  {
    id: 3,
    title: "Pepperoni Pizza",
    img: "/images/pizza.webp",
    desc: "Tomato sauce, mozzarella, pepperoni",
    prices: [11, 12, 13],
  },
  {
    id: 4,
    title: "Hawaiian Pizza",
    img: "/images/pizza.webp",
    desc: "Tomato sauce, mozzarella, ham, pineapple",
    prices: [12, 13, 14],
  },
  {
    id: 5,
    title: "Meat Lover's Pizza",
    img: "/images/pizza.webp",
    desc: "Tomato sauce, mozzarella, sausage, bacon, pepperoni",
    prices: [14, 15, 16],
  },
  {
    id: 6,
    title: "Veggie Pizza",
    img: "/images/pizza.webp",
    desc: "Tomato sauce, mozzarella, bell peppers, mushrooms, onions, olives",
    prices: [12, 13, 14],
  },
  {
    id: 7,
    title: "Chicken Pizza",
    img: "/images/pizza.webp",
    desc: "Tomato sauce, mozzarella, chicken, onions, bell peppers",
    prices: [12, 13, 14],
  },
  {
    id: 8,
    title: "BBQ Chicken Pizza",
    img: "/images/pizza.webp",
    desc: "Tomato sauce, mozzarella, chicken, onions, bell peppers, BBQ sauce",
    prices: [13, 14, 15],
  },
  {
    id: 9,
    title: "Chicken Alfredo Pizza",
    img: "/images/pizza.webp",
    desc: "Alfredo sauce, mozzarella, chicken, onions, bell peppers",
    prices: [13, 14, 15],
  },
  {
    id: 10,
    title: "Chicken Supreme Pizza",
    img: "/images/pizza.webp",
    desc: "Tomato sauce, mozzarella, chicken, onions, bell peppers, mushrooms",
    prices: [13, 14, 15],
  },
  {
    id: 11,
    title: "Chicken Bacon Ranch Pizza",
    img: "/images/pizza.webp",
    desc: "Tomato sauce, mozzarella, chicken, bacon, ranch",
    prices: [13, 14, 15],
  },
  {
    id: 12,
    title: "Chicken Carbonara Pizza",
    img: "/images/pizza.webp",
    desc: "Carbonara sauce, mozzarella, chicken, onions, bell peppers",
    prices: [13, 14, 15],
  },
];
